### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by oej** [jakgibb/parse-iptables-log#1]
Looks like something I've been looking for. If you clarify your license it will be easier to build on it and use it in a commercial or non-commercial environment. 

Thank you!

/Olle

**Comment by jakgibb** [comment]
Hi Ollej,

The script isn't fantastic, it was just a quick and dirty solution but glad it's working for you.
As for a license, do absolutely whatever you want with the code, commercial or non-commercial, redistribute it as you please, sell it our modify it, no credit required.
Hope that helps.

Edit:
Added a LICENSE.txt to clarify

**Comment by oej** [comment]
Thanks!
